In [2]:
import pickle
import numpy as np

In [3]:
ohe_sex = pickle.load(open("ohe_sex.pkl", "rb"))
ohe_emb = pickle.load(open("ohe_emb.pkl", "rb"))
clf = pickle.load(open("clf.pkl", "rb"))

In [5]:
# input
# pclass, sex, age, sibsp, parch, fare, embarked
test_input = np.array([2, "male", 31.0,0, 0, 10.5, "S"], dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [8]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

C:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [9]:
test_input_emb = ohe_emb.transform(test_input[:,-1].reshape(1,1))
test_input_emb

array([[0., 0., 1.]])

In [10]:
test_input_age = test_input[:,2].reshape(1,1)

In [14]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]], test_input_sex, test_input_emb, test_input_age), axis=1)

In [15]:
test_input_transformed

array([[2, 0, 0, 10.5, 0.0, 1.0, 0.0, 0.0, 1.0, 31.0]], dtype=object)

In [16]:
test_input_transformed.shape

(1, 10)

In [17]:
clf.predict(test_input_transformed)

array([1], dtype=int64)