In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_diabetes

In [4]:
X, y = load_diabetes(return_X_y=True)

In [8]:
print(X.shape)
X

(442, 10)


array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [9]:
y.shape

(442,)

# Multiple Linear Regression Using Sklearn 

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

In [23]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)

(353, 10)
(353,)
(89, 10)


In [24]:
reg = LinearRegression()

In [25]:
reg.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = reg.predict(X_test)

In [27]:
r2_score(y_test, y_pred)

0.4588389962630465

In [28]:
reg.coef_

array([  -19.84569955,  -271.44799521,   518.60568284,   326.13921989,
       -1003.87022985,   624.04203978,   220.7339424 ,   263.93739547,
         829.85679767,    77.75019971])

In [29]:
reg.intercept_

151.5282462062113

# Making our own Multiple linear regression class

In [53]:
class yooLR:

    def __init__(self):
        self.coef_ =  None
        self.intercept_ = None

    def fit(self, X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)

        # calculating the coefffs
        beta = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        self.coef_ = beta[1:]
        self.intercept_ = beta[0]
        
    def predict(self, X_test):
        
        return self.intercept_ + np.dot(self.coef_, X_test)

In [54]:
lr = yooLR()

In [55]:
lr.fit(X_train, y_train)

In [56]:
lr.coef_

array([  -19.84569955,  -271.44799521,   518.60568284,   326.13921989,
       -1003.87022985,   624.04203978,   220.7339424 ,   263.93739547,
         829.85679767,    77.75019971])

In [57]:
lr.intercept_

151.52824620621132

In [58]:
y_pred = lr.predict(X_test)

ValueError: shapes (10,) and (89,10) not aligned: 10 (dim 0) != 89 (dim 0)

In [39]:
X_train

array([[ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       [ 0.00538306,  0.05068012, -0.00189471, ..., -0.00259226,
         0.03839393, -0.01350402],
       [-0.00188202, -0.04464164,  0.05415152, ...,  0.08486339,
         0.08449153,  0.04862759],
       ...,
       [ 0.00538306,  0.05068012, -0.00836158, ...,  0.03430886,
         0.01255119,  0.09419076],
       [-0.0382074 ,  0.05068012,  0.07139652, ...,  0.071948  ,
         0.05028067,  0.06933812],
       [-0.0382074 , -0.04464164,  0.00996123, ..., -0.03949338,
        -0.01599887, -0.04249877]])

In [41]:
print(np.insert(X_train, 0, 1, axis=1).shape)
np.insert(X_train, 0, 1, axis=1)

(353, 11)


array([[ 1.        ,  0.08529891,  0.05068012, ..., -0.00259226,
         0.00286131, -0.02593034],
       [ 1.        ,  0.00538306,  0.05068012, ..., -0.00259226,
         0.03839393, -0.01350402],
       [ 1.        , -0.00188202, -0.04464164, ...,  0.08486339,
         0.08449153,  0.04862759],
       ...,
       [ 1.        ,  0.00538306,  0.05068012, ...,  0.03430886,
         0.01255119,  0.09419076],
       [ 1.        , -0.0382074 ,  0.05068012, ...,  0.071948  ,
         0.05028067,  0.06933812],
       [ 1.        , -0.0382074 , -0.04464164, ..., -0.03949338,
        -0.01599887, -0.04249877]])